variables:
  ARM_PASS: $(adminpass)

trigger:
- none

pool: 'linux'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '101-webapp-managed-mysql'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMME'
    subscriptionId: 'fd0b5651-02f6-4896-a0ac-782eea8f60c8'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipelinesDAVE-rg'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'